name: Django CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-scan:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: sri
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      DB_HOST: 127.0.0.1
      DB_NAME: vardaan
      DB_USER: vardaan_user
      DB_PASSWORD: vardaan_pass

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install MySQL Client
      run: sudo apt-get update && sudo apt-get install -y default-mysql-client

    - name: Wait for MySQL to be ready
      run: |
        until mysqladmin ping -h 127.0.0.1 -u root -proot --silent; do
          echo "Waiting for MySQL..."
          sleep 5
        done

    - name: Create database if not exists
      run: |
        mysql -h 127.0.0.1 -u root -proot -e "CREATE DATABASE IF NOT EXISTS vardaan;"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Migrations
      run: |
        python manage.py migrate

    - name: Run Unit Tests
      run: |
        python manage.py test

    - name: Run Bandit Security Scan
      run: |
        bandit -r . -lll -ii

    - name: Run Semgrep Static Code Scan
      uses: returntocorp/semgrep-action@v1
      with:
        config: "p/ci"

    - name: Run Snyk Scan
      uses: snyk/actions/python@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --file=requirements.txt --sarif-file-output=snyk.sarif

    - name: Upload Snyk SARIF to GitHub
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk.sarif
